version: '2'
services:
  server:
    build: ..
    image: sandinh/ambry
    ports:
#    com.github.ambry.config.NetworkConfig.port
      - 6667:6667
    volumes:
      - /home/docker/ambry-docker/sample/config:/opt/ambry/config
      - /mnt/sda1/ambry_data:/opt/ambry/data
    command: ["java",
      "-Dlog4j.configuration=file:/opt/ambry/config/log4j.properties",
      "-cp", "ambry.jar",
      "com.github.ambry.server.AmbryMain",
      "--serverPropsFilePath", "/opt/ambry/config/server.properties",
      "--hardwareLayoutFilePath", "/opt/ambry/config/HardwareLayout.json",
      "--partitionLayoutFilePath", "/opt/ambry/config/PartitionLayout.json"
    ]
  frontend:
    image: sandinh/ambry
    ports:
#    com.github.ambry.config.NettyConfig.nettyServerPort
      - 1174:1174
    volumes:
      - /home/docker/ambry-docker/sample/config:/opt/ambry/config
      - /mnt/sda1/ambry_data:/opt/ambry/data
    command: ["java",
      "-Dlog4j.configuration=file:/opt/ambry/config/log4j.properties",
      "-cp", "ambry.jar",
      "com.github.ambry.frontend.AmbryFrontendMain",
      "--serverPropsFilePath", "/opt/ambry/config/frontend.properties",
      "--hardwareLayoutFilePath", "/opt/ambry/config/HardwareLayout.json",
      "--partitionLayoutFilePath", "/opt/ambry/config/PartitionLayout.json"
    ]
